service: river-trail-alerts

provider:
  name: aws
  runtime: python3.8
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action: "*"
      Resource:
        Fn::GetAtt:
          - RiverTrailAlertsTable
          - Arn

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  update:
    handler: handler.handle
    events:
      - schedule: rate(30 minutes)

resources:
  Resources:
    RiverTrailAlertsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "RiverTrailAlertsTable"
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: "S"
          - AttributeName: "sk"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "pk"
            KeyType: "HASH"
          - AttributeName: "sk"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 2

